name: CI tests

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8, 3.9, "3.10", "3.11"]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    # - name: Cache pip
    #   uses: actions/cache@v2
    #   with:
    #     path: ~/.cache/pip  # This path is specific to Ubuntu
    #     # Look to see if there is a cache hit for the corresponding requirements file
    #     key: ${{ runner.os }}-pip-${{ hashFiles('requirements-development.txt') }}
    #     restore-keys: |
    #       ${{ runner.os }}-pip-
    #       ${{ runner.os }}-
    - name: Install dependencies
      run: pip install -r requirements-development.txt
    - name: Standardize code formatting with black
      run: black --check .
    - name: Static analysis with mypy
      run: mypy ofxtools tests
    - name: Test with nose
      run: nose2 -s tests --verbose --with-coverage --fail-fast --output-buffer
